### ISSUE TITLE
WebComponent doesn't work in Firefox

### ISSUE THREAD

**Issue by jensgro** [daviddarnes/component-template#1]
In Firefox the general example isn't shown while in Chrome all three examples are buttons. There is no fallbnack shown in Chrome.

**Expected behaviour**
I expect Firefox to show a button in the general examples and to not show buttons in Chrome in the steps two and three.

**Screenshot**

![image](https://github.com/daviddarnes/component-template/assets/214849/fd1e61b1-d748-4e2a-b406-683786c7c5e0)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FF 
 - Version 121.0

**Comment by daviddarnes** [comment]
I assume this issue was meant for [the `share-button` component](https://github.com/daviddarnes/share-button). This is working as designed, [Firefox does not support `navigator.share`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility) so the component won't initialise and instead the examples will show the fallback options

**Comment by jensgro** [comment]
You are right. Sorry :-)
